import { Restaurant } from "./types";

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=70`;

/**
 * Mock restaurant + reel dataset. Posters use Unsplash; the UI always renders a
 * cuisine-keyed gradient + emoji underneath so it looks good even offline.
 */
export const RESTAURANTS: Restaurant[] = [
  {
    id: "tonys-slice",
    name: "Tony's Coal Oven",
    cuisines: ["Italian"],
    price: 2,
    rating: 9.1,
    popularity: 0.92,
    neighborhood: "West Village",
    city: "New York",
    distanceKm: 1.2,
    vibes: ["cozy", "casual", "date-night"],
    dietary: ["vegetarian"],
    spice: 0,
    tags: ["wood-fired", "natural wine", "famous crust"],
    signatureDishes: ["Burrata pie", "Spicy soppressata", "Garlic knots"],
    blurb:
      "Blistered coal-oven pies with a 72-hour cold-fermented crust. The line is worth it.",
    reels: [
      {
        id: "r-tony-1",
        poster: img("1565299624946-b28f40a0ae38"),
        gradient: ["#ff8a00", "#e52e71"],
        emoji: "🍕",
        caption: "The cheese pull on this burrata pie is illegal 🧀🔥",
        author: "@crustcrusader",
        likes: 24213,
        dish: "Burrata pie",
      },
      {
        id: "r-tony-2",
        poster: img("1513104890138-7c749659a591"),
        gradient: ["#f7971e", "#ffd200"],
        emoji: "🔥",
        caption: "POV: you finally got a table at Tony's",
        author: "@nycbites",
        likes: 9821,
        dish: "Spicy soppressata",
      },
    ],
  },
  {
    id: "ramen-koba",
    name: "Ramen Koba",
    cuisines: ["Japanese"],
    price: 2,
    rating: 9.4,
    popularity: 0.95,
    neighborhood: "East Village",
    city: "New York",
    distanceKm: 0.8,
    vibes: ["late-night", "casual", "hidden-gem"],
    dietary: [],
    spice: 2,
    tags: ["tonkotsu", "12-hour broth", "counter seating"],
    signatureDishes: ["Black garlic tonkotsu", "Spicy miso", "Karaage"],
    blurb:
      "A 9-seat counter slinging silky 12-hour tonkotsu until 2am. Slurp loud.",
    reels: [
      {
        id: "r-koba-1",
        poster: img("1591814468924-caf88d1232e1"),
        gradient: ["#200122", "#6f0000"],
        emoji: "🍜",
        caption: "12-hour broth that hits different at midnight 🌙",
        author: "@slurpsquad",
        likes: 51204,
        dish: "Black garlic tonkotsu",
      },
      {
        id: "r-koba-2",
        poster: img("1569718212165-3a8278d5f624"),
        gradient: ["#42275a", "#734b6d"],
        emoji: "🔥",
        caption: "spice level: regret. worth it.",
        author: "@heatseeker",
        likes: 18430,
        dish: "Spicy miso",
      },
    ],
  },
  {
    id: "la-tacolab",
    name: "TacoLab",
    cuisines: ["Mexican"],
    price: 1,
    rating: 8.8,
    popularity: 0.88,
    neighborhood: "Mission",
    city: "San Francisco",
    distanceKm: 2.1,
    vibes: ["casual", "quick-bite", "late-night", "group-friendly"],
    dietary: ["gluten-free", "vegetarian"],
    spice: 3,
    tags: ["al pastor", "handmade tortillas", "salsa bar"],
    signatureDishes: ["Al pastor", "Birria quesataco", "Elote"],
    blurb: "Trompo-carved al pastor on nixtamal tortillas. The birria consommé is a religion.",
    reels: [
      {
        id: "r-taco-1",
        poster: img("1565299585323-38d6b0865b47"),
        gradient: ["#f12711", "#f5af19"],
        emoji: "🌮",
        caption: "the birria dip in 4k 🤤",
        author: "@tacotuesdaily",
        likes: 88210,
        dish: "Birria quesataco",
      },
      {
        id: "r-taco-2",
        poster: img("1552332386-f8dd00dc2f85"),
        gradient: ["#cb2d3e", "#ef473a"],
        emoji: "🔥",
        caption: "trompo carving asmr",
        author: "@streetfoodsf",
        likes: 33120,
        dish: "Al pastor",
      },
    ],
  },
  {
    id: "bangkok-soi",
    name: "Soi 47",
    cuisines: ["Thai"],
    price: 2,
    rating: 9.0,
    popularity: 0.83,
    neighborhood: "Silver Lake",
    city: "Los Angeles",
    distanceKm: 3.4,
    vibes: ["trendy", "date-night", "group-friendly"],
    dietary: ["vegetarian", "vegan", "gluten-free"],
    spice: 3,
    tags: ["northern thai", "khao soi", "tom yum"],
    signatureDishes: ["Khao soi", "Crispy pork boat noodles", "Mango sticky rice"],
    blurb: "Bold northern-Thai heat in a neon-lit room. The khao soi will change you.",
    reels: [
      {
        id: "r-soi-1",
        poster: img("1455619452474-d2be8b1e70cd"),
        gradient: ["#11998e", "#38ef7d"],
        emoji: "🍛",
        caption: "khao soi pull 🧡 northern thai supremacy",
        author: "@spicemaps",
        likes: 27750,
        dish: "Khao soi",
      },
    ],
  },
  {
    id: "delhi-streets",
    name: "Delhi Streets",
    cuisines: ["Indian"],
    price: 2,
    rating: 8.7,
    popularity: 0.79,
    neighborhood: "Curry Hill",
    city: "New York",
    distanceKm: 1.9,
    vibes: ["casual", "cozy", "group-friendly"],
    dietary: ["vegetarian", "vegan", "halal"],
    spice: 3,
    tags: ["chaat", "tandoor", "thali"],
    signatureDishes: ["Butter chicken", "Pani puri", "Garlic naan"],
    blurb: "Street-style chaat and a tandoor that never stops. Get the pani puri.",
    reels: [
      {
        id: "r-delhi-1",
        poster: img("1585937421612-70a008356fbe"),
        gradient: ["#f7971e", "#ffd200"],
        emoji: "🍛",
        caption: "butter chicken + garlic naan = elite combo",
        author: "@masalamood",
        likes: 41200,
        dish: "Butter chicken",
      },
    ],
  },
  {
    id: "seoul-fire",
    name: "Seoul Fire BBQ",
    cuisines: ["Korean", "BBQ"],
    price: 3,
    rating: 9.2,
    popularity: 0.9,
    neighborhood: "Koreatown",
    city: "Los Angeles",
    distanceKm: 4.0,
    vibes: ["group-friendly", "late-night", "trendy"],
    dietary: [],
    spice: 2,
    tags: ["tabletop grill", "galbi", "banchan"],
    signatureDishes: ["Galbi short rib", "Pork belly", "Kimchi jjigae"],
    blurb: "Tabletop grills, endless banchan, and galbi that caramelizes like candy.",
    reels: [
      {
        id: "r-seoul-1",
        poster: img("1632558319133-e896f5a5b41a"),
        gradient: ["#cb356b", "#bd3f32"],
        emoji: "🥩",
        caption: "the galbi sizzle 🔥 KBBQ with the crew >>>",
        author: "@grillgang",
        likes: 64310,
        dish: "Galbi short rib",
      },
    ],
  },
  {
    id: "blue-smoke",
    name: "Blue Smoke Pit",
    cuisines: ["BBQ", "American"],
    price: 2,
    rating: 8.9,
    popularity: 0.81,
    neighborhood: "Downtown",
    city: "Austin",
    distanceKm: 5.2,
    vibes: ["casual", "group-friendly", "outdoor"],
    dietary: ["gluten-free"],
    spice: 1,
    tags: ["brisket", "16-hour smoke", "post oak"],
    signatureDishes: ["Fatty brisket", "Pork ribs", "Jalapeño cheese sausage"],
    blurb: "Post-oak smoked brisket with a bark that snaps. Sells out by 1pm.",
    reels: [
      {
        id: "r-smoke-1",
        poster: img("1529193591184-b1d58069ecdd"),
        gradient: ["#3e5151", "#decba4"],
        emoji: "🍖",
        caption: "brisket slice that wobbles. texas forever 🤠",
        author: "@smokering",
        likes: 39870,
        dish: "Fatty brisket",
      },
    ],
  },
  {
    id: "cafe-lune",
    name: "Café Lune",
    cuisines: ["Cafe", "French", "Dessert"],
    price: 2,
    rating: 8.6,
    popularity: 0.74,
    neighborhood: "Nob Hill",
    city: "San Francisco",
    distanceKm: 2.6,
    vibes: ["cozy", "date-night", "outdoor"],
    dietary: ["vegetarian"],
    spice: 0,
    tags: ["croissants", "matcha", "natural light"],
    signatureDishes: ["Pistachio croissant", "Matcha latte", "Basque cheesecake"],
    blurb: "Laminated-pastry heaven with the dreamiest matcha and a sunlit patio.",
    reels: [
      {
        id: "r-lune-1",
        poster: img("1509042239860-f550ce710b93"),
        gradient: ["#a8c0ff", "#3f2b96"],
        emoji: "🥐",
        caption: "pistachio croissant flat lay 🍵 soft life",
        author: "@pastrypilgrim",
        likes: 21540,
        dish: "Pistachio croissant",
      },
    ],
  },
  {
    id: "el-mar",
    name: "El Mar",
    cuisines: ["Seafood", "Spanish", "Mediterranean"],
    price: 3,
    rating: 9.0,
    popularity: 0.77,
    neighborhood: "Wynwood",
    city: "Miami",
    distanceKm: 6.1,
    vibes: ["trendy", "date-night", "outdoor"],
    dietary: ["gluten-free", "dairy-free"],
    spice: 1,
    tags: ["paella", "crudo", "raw bar"],
    signatureDishes: ["Seafood paella", "Hamachi crudo", "Grilled octopus"],
    blurb: "Coastal Spanish small plates and a socarrat-crusted paella for the table.",
    reels: [
      {
        id: "r-elmar-1",
        poster: img("1534080564583-6be75777b70a"),
        gradient: ["#2193b0", "#6dd5ed"],
        emoji: "🦐",
        caption: "paella socarrat scrape >>> the crispy bottom is the prize",
        author: "@seafoodiary",
        likes: 30210,
        dish: "Seafood paella",
      },
    ],
  },
  {
    id: "green-root",
    name: "Green Root",
    cuisines: ["Vegan", "Mediterranean"],
    price: 2,
    rating: 8.5,
    popularity: 0.68,
    neighborhood: "Capitol Hill",
    city: "Seattle",
    distanceKm: 3.0,
    vibes: ["cozy", "casual", "quick-bite"],
    dietary: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    spice: 1,
    tags: ["plant-based", "mezze", "grain bowls"],
    signatureDishes: ["Harissa cauliflower", "Mezze board", "Mushroom shawarma"],
    blurb: "Plant-based mezze that even carnivores rave about. The harissa cauli is a star.",
    reels: [
      {
        id: "r-green-1",
        poster: img("1540420773420-3366772f4999"),
        gradient: ["#56ab2f", "#a8e063"],
        emoji: "🥗",
        caption: "vegan mezze board glow up 🌿",
        author: "@plantplates",
        likes: 17800,
        dish: "Mezze board",
      },
    ],
  },
  {
    id: "pho-89",
    name: "Phở 89",
    cuisines: ["Vietnamese"],
    price: 1,
    rating: 8.8,
    popularity: 0.8,
    neighborhood: "Eastlake",
    city: "Seattle",
    distanceKm: 2.4,
    vibes: ["casual", "cozy", "quick-bite"],
    dietary: ["gluten-free", "dairy-free"],
    spice: 2,
    tags: ["bone broth", "banh mi", "rare beef"],
    signatureDishes: ["Phở tái", "Bánh mì", "Spring rolls"],
    blurb: "24-hour bone broth phở that fixes everything. Add the rare beef.",
    reels: [
      {
        id: "r-pho-1",
        poster: img("1582878826629-29b7ad1cdc43"),
        gradient: ["#603813", "#b29f94"],
        emoji: "🍲",
        caption: "broth pour + rare beef poach. cozy season 🍂",
        author: "@brothbabe",
        likes: 25600,
        dish: "Phở tái",
      },
    ],
  },
  {
    id: "dumpling-dynasty",
    name: "Dumpling Dynasty",
    cuisines: ["Chinese"],
    price: 2,
    rating: 9.1,
    popularity: 0.86,
    neighborhood: "Chinatown",
    city: "New York",
    distanceKm: 1.5,
    vibes: ["casual", "group-friendly", "hidden-gem"],
    dietary: ["vegetarian"],
    spice: 2,
    tags: ["xiao long bao", "hand-pulled noodles", "dim sum"],
    signatureDishes: ["Soup dumplings", "Dan dan noodles", "Scallion pancake"],
    blurb: "18-fold soup dumplings and hand-pulled noodles slapped to order.",
    reels: [
      {
        id: "r-dump-1",
        poster: img("1496116218417-1a781b1c416c"),
        gradient: ["#ee9ca7", "#ffdde1"],
        emoji: "🥟",
        caption: "soup dumpling first bite. mind the lava 🌋",
        author: "@xlbdaily",
        likes: 47210,
        dish: "Soup dumplings",
      },
    ],
  },
  {
    id: "smashville",
    name: "Smashville",
    cuisines: ["American"],
    price: 1,
    rating: 8.6,
    popularity: 0.89,
    neighborhood: "Downtown",
    city: "Chicago",
    distanceKm: 1.0,
    vibes: ["casual", "quick-bite", "late-night"],
    dietary: [],
    spice: 1,
    tags: ["smash burger", "crispy edges", "milkshakes"],
    signatureDishes: ["Double smash", "Bacon jam burger", "Vanilla malt"],
    blurb: "Lacy-edged smash burgers on a buttered potato bun. Get the double.",
    reels: [
      {
        id: "r-smash-1",
        poster: img("1568901346375-23c9450c58cd"),
        gradient: ["#c31432", "#240b36"],
        emoji: "🍔",
        caption: "smash + sear + cheese skirt = perfection",
        author: "@burgermeta",
        likes: 72340,
        dish: "Double smash",
      },
    ],
  },
  {
    id: "addis-red",
    name: "Addis Red",
    cuisines: ["Ethiopian"],
    price: 2,
    rating: 8.9,
    popularity: 0.62,
    neighborhood: "U Street",
    city: "Washington DC",
    distanceKm: 4.5,
    vibes: ["cozy", "group-friendly", "hidden-gem"],
    dietary: ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    spice: 2,
    tags: ["injera", "berbere", "communal"],
    signatureDishes: ["Doro wat", "Veggie combo", "Kitfo"],
    blurb: "Hand-torn injera and slow-simmered berbere stews meant to be shared.",
    reels: [
      {
        id: "r-addis-1",
        poster: img("1567188040759-fb8a883dc6d8"),
        gradient: ["#c94b4b", "#4b134f"],
        emoji: "🫓",
        caption: "veggie combo on injera, eat with your hands 🤝",
        author: "@injeralove",
        likes: 14210,
        dish: "Veggie combo",
      },
    ],
  },
];

export const getRestaurant = (id: string) =>
  RESTAURANTS.find((r) => r.id === id);

export const ALL_CUISINES = Array.from(
  new Set(RESTAURANTS.flatMap((r) => r.cuisines)),
).sort();
