import { Cuisine, Restaurant } from "./types";
import generated from "./restaurants.generated.json";

/**
 * Real Chicago restaurant dataset, generated by `npm run ingest` from the
 * Google Places API (see scripts/ingest.ts). Regenerate + commit to refresh.
 * The cast is required because JSON widens string-literal unions to `string`.
 */
export const RESTAURANTS = generated as unknown as Restaurant[];

/**
 * id → Restaurant index, built once. Lets `getRestaurant` and the recommender's
 * affinity lookups be O(1) instead of an O(n) scan per id — meaningful now that
 * the dataset is ~1.6k records and history lookups run inside scoring.
 */
export const RESTAURANTS_BY_ID: ReadonlyMap<string, Restaurant> = new Map(
  RESTAURANTS.map((r) => [r.id, r]),
);

export const getRestaurant = (id: string) => RESTAURANTS_BY_ID.get(id);

export const ALL_CUISINES: Cuisine[] = Array.from(
  new Set(RESTAURANTS.flatMap((r) => r.cuisines)),
).sort() as Cuisine[];
