import { Cuisine, Restaurant } from "./types";
import generated from "./restaurants.generated.json";

/**
 * Real Chicago restaurant dataset, generated by `npm run ingest` from the
 * Google Places API (see scripts/ingest.ts). Regenerate + commit to refresh.
 * The cast is required because JSON widens string-literal unions to `string`.
 */
export const RESTAURANTS = generated as unknown as Restaurant[];

export const getRestaurant = (id: string) =>
  RESTAURANTS.find((r) => r.id === id);

export const ALL_CUISINES: Cuisine[] = Array.from(
  new Set(RESTAURANTS.flatMap((r) => r.cuisines)),
).sort() as Cuisine[];
